# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: redis-cache
# spec:
#   selector:
#     matchLabels:
#       app: store
#   replicas: 6
#   template:
#     metadata:
#       labels:
#         app: store
#     spec:
#       affinity:
#         podAntiAffinity:
#           preferredDuringSchedulingIgnoredDuringExecution:
#           - podAffinityTerm:
#               labelSelector:
#                 matchExpressions:
#                 - { key: app,operator: In,values: [store] }
#               topologyKey: "kubernetes.io/region"
#             weight: 1
#       containers:
#       - name: redis-server
#         image: redis:3.2-alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  selector:
    matchLabels:
      app: store
  replicas: 6
  template:
    metadata:
      labels:
        app: store
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - { key: app,operator: In,values: [store] }
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: redis-server
        image: redis:3.2-alpine