apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 3
            preference:
              matchExpressions: 
              - key: gpu
                operator: In
                values:
                - enabled
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
# spec:
#   selector:
#     matchLabels:
#       app: nginx
#   replicas: 6
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec: 
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions: 
#               - key: gpu
#                 operator: In
#                 values:
#                 - enabled
#       containers:
#       - name: nginx
#         image: nginx
#         ports:
#         - containerPort: 80